version: '2'
services:
  backend:
    build: backend
    ports:
      - "8080:8080"
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/code/src
      - /project/node_modules
    depends_on:
      - backend
  telegram-bot:
    build: telegram-bot
    ports:
      - "80:80"
    depends_on:
      - backend