version: '2'
services:
  telegram-bot:
    build: telegram-bot
    ports:
      - "8081:8081"
  backend:
    build: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/code/src
      - /project/node_modules
    depends_on:
      - backend
  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
