version: '3'
services:
  telegram-bot:
    build: telegram-bot
    ports:
      - "8081:8081"
  backend:
    build: backend
    image: empanadapp.azurecr.io/backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  frontend:
    build: frontend
    image: empanadapp.azurecr.io/frontend
    env_file:
      - frontend/.env
    ports:
      - "80:80"
    depends_on:
      - backend
  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - "27017:27017"