package com.example.telegrambot;

public enum UserState {
    WAITING_SHARE_ID,
    WAITING_ID,
    WAITING_PASSWORD,
    LOGGED_IN,
    WAITING_ITEM_DESCRIPTION,
    WAITING_ITEM_QUANTITY,
    LOGGED_OUT,
    WAITING_USERNAME_SIGNUP,
    WAITING_EMAIL_SIGNUP,
    WAITING_PASSWORD_SIGNUP
}
